### ISSUE TITLE
Android Graphhopper : An error happend while creating graph:Version of nodes unsupported: 4, expected: 3

### ISSUE THREAD

**Issue by chrizzz35** [graphhopper/graphhopper#456]
Hi guys, i'm sorry if there any duplicate post, 
but I've tried to solve this for week and search for the solution, but haven't got it till now. 

I have a problem when trying to run code from here : https://github.com/graphhopper/graphhopper/tree/master/android

I've read for multiple times from here too guys : 
https://github.com/graphhopper/graphhopper/blob/master/docs/android/index.md

This is what I've done after import the project to eclipse :

I download the jars based on build.gradle which is : 

    dependencies {
        compile(group: 'com.graphhopper', name: 'graphhopper', version: '0.4-SNAPSHOT') {
           exclude group: 'com.google.protobuf', module: 'protobuf-java'
           exclude group: 'org.openstreetmap.osmosis', module: 'osmosis-osm-binary'
           exclude group: 'org.apache.xmlgraphics', module: 'xmlgraphics-commons'
        }

        compile group: 'org.mapsforge', name: 'mapsforge-core', version: '0.5.1'
        compile group: 'org.mapsforge', name: 'mapsforge-map', version: '0.5.1'
        compile group: 'org.mapsforge', name: 'mapsforge-map-android', version: '0.5.1'
        compile group: 'org.mapsforge', name: 'mapsforge-map-reader', version: '0.5.1'

        compile group: 'org.slf4j', name: 'slf4j-android', version: '1.7.10'
        compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.10'
    }

then I see this code in MainActivity.java :
private String fileListURL = "https://graphhopper.com/public/maps/0.5/";

I can compile & run this, and I download the maps from the apps. 
But when the apps try to load the maps, it toast an error message : 
<code>An error happend while creating graph:Version of nodes unsupported: 4, expected: 3</code>

I've tried to change the fileListURL to 0.1, 0.2, 0.3, 0.4, and 0.5, but got the same error

FYI : 
################################
List Jars :
- graphhopper 0.4-snapshot
- mapsforge core 0.5.1
- mapsforge map 0.5.1
- mapsforge map android 0.5.1
- mapsforge map reader 0.5.1
- osmosis osm binary 0.4.3
- protobuf java 2.4.1
- slf4j android 1.7.10 
- slf4j api 1.7.10
- xmlgraphic commons 1.4

Hope you guys can help me to solve this problem, Thank you

**Comment by karussell** [comment]
This is due to the problem mentioned in comment https://github.com/graphhopper/graphhopper/pull/453#issuecomment-117240068

**Comment by karussell** [comment]
Forgot to mention that this should be fixed as over night new graphs were created. Please remove the folders on Android and download again.

Now also it looks like you have an old 0.5 installed, make sure you really refresh your build/jar/repo.

> I've tried to change the fileListURL to 0.1, 0.2, 0.3, 0.4, and 0.5, but got the same error

It should be a slightly different error message with different versions

**Comment by chrizzz35** [comment]
Thanks karussell, for your quick responses

Yes this is true 
<code>I've tried to change the fileListURL to 0.1, 0.2, 0.3, 0.4, and 0.5, but got the same error</code>
It return different same toast, but different version. Sorry for my bad description. 

And I still dont get about the build/jar/repo things.  (nodes version 3)
Is there any wrong jar or the wrong version? If I may know, which one is it? 

Thank you, karussell

**Comment by karussell** [comment]
> graphhopper 0.4-snapshot

This is the problem: use a stable jar 0.4.1 or 0.5-SNAPSHOT

**Comment by karussell** [comment]
Also discussion or setup problems should be discussed on the mailing list instead (although in this case partly a real problem ;))

**Comment by devemux86** [comment]
It's always recommended to use the same GraphHopper version for building graphs and for reading them (due to possible graph structure changes).
