### ISSUE TITLE
Wrong: Fastest through residential and not over secondary

### ISSUE THREAD

**Issue by AllroadsNL** [graphhopper/graphhopper#511]
https://graphhopper.com/maps/?point=52.701666%2C5.861721&point=52.711957%2C5.867118&locale=nl-NL&layer=Omniscale

This is wrong, taking two turns extra over residential Breestraat, this cost extra time, and over residential road.

The whole village is 30km/h. also secondary.

Allroads

**Comment by boldtrn** [comment]
I just tested the above url and the result looks correct to me. Probably the data was fixed?

However, I found another example, that shows exactly the same [behavior](https://graphhopper.com/maps/?point=48.669007%2C9.458435&point=48.66725%2C9.457855&locale=de-DE&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale). The main street is 30kmh, whereas the other road is [residential](http://www.openstreetmap.org/way/34877065#map=18/48.66808/9.45821&layers=ND) with no entered speed limit, but GH default is 30 as well. Even more interestingly, using the residential road is 208m whereas using the main road is 204m. A very small part of the main street is even [50kmh](http://www.openstreetmap.org/way/390056607#map=19/48.66795/9.45834&layers=ND), but I am not sure if this might be related?

**Comment by karussell** [comment]
@boldtrn thanks for the example. This is strange as the residential should use default value of 30 and the other road has a max_speed=30 so the shortest one should be preferred.

@AllroadsNL Also strange that I do not remember this issue and never commented on it as it is related to #230 and I normally at least comment what to do or what not. Sorry about this.

**Comment by AllroadsNL** [comment]
@boldtrn No, data fix, as I can see.
@karussell , no problem we do it together, sometimes some, fall between ship and wall.

**Comment by karussell** [comment]
Why do you think it is not fixed? Can you provide a GH Maps link with via points to show how you'd want it?

**Comment by AllroadsNL** [comment]
The question was:

> I just tested the above url and the result looks correct to me. Probably the data was fixed?

 If the osm data was changed. No. This is not graphhopper software, this must be changed, meanwhile.

**Comment by boldtrn** [comment]
I just found another [example](https://graphhopper.com/maps/?point=-33.678555%2C151.303432&point=-33.680533%2C151.30282&locale=de-DE&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale) that seems to be of the same kind. The root for that is probably that the max speed was missing on a small [way](http://www.openstreetmap.org/way/172423349). I fixed the data, so the issue should disappear soon.

**Comment by boldtrn** [comment]
Here is another interesting [example](https://graphhopper.com/maps/?point=48.984597%2C10.643456&point=48.993608%2C10.653219). The reason for this is that the tracks are tagged with maxspeed=100.

**Comment by boldtrn** [comment]
Just found one more strange [example](https://graphhopper.com/maps/?point=48.70519%2C9.886875&point=48.704585%2C9.888344). The main street is 30, the other streets are residential as well. Somehow, we take the detour through residential, even though it is 17m longer.

**Comment by karussell** [comment]
> Somehow, we take the detour through residential, even though it is 17m longer.

This is probably related to https://github.com/graphhopper/directions-api/issues/59 will have a look
